# Site settings
title: orangelop
brief-intro: Code is poetry.
small_introduction: Chinese, Senior High Student, Frontend & Semi-backend Programmer, Founder & Owner of <em>LME</em>. 
# Frontend & Backend, Python, Linux, Electronic music, Mathematics, Physics, Chemistry
welcome: Welcome to my blog (｡･∀･)ﾉﾞ!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://orangelop.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# 其他链接
twitter_username: orangelop_
github_username: Orangelop
telegram_username: Orangelop
email: orangelop@qq.com

# 页尾介绍
description_footer: 

# 评论
disqus_comments_shortname:
# orangelop-blog
google_analytics_id:
# G-54SGB2GV90
# 2022/10/15 not avaliable in CN

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# category/tgs 地址
category_dir: category/
tag_dir: tags/

# excerpt
excerpt_separator: "\n\n\n\n"

# 分页
gems: [jekyll-paginate]
paginate: 8

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate
  
# port
port: 12345